#!/usr/bin/env bash

function explode {
	echo "$1" | fold -w 1 | tail -n +2 | awk '{ print "-"$1 }'
}

function through {
	echo "$1"
}

function express {
	[[ "$1" =~ ^-[a-z0-9]+$ ]] && explode "$1" || through "$1"
}

for argument in "$@"; do express "$argument"; done
